# -*- coding: utf-8 -*-
"""1158번_요세푸스 문제.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hu-OWPyxM3Buo05a-GxQZAPutusIgHpV


N, K=map(int, input().split())
answer=[]
arr=[i for i in range(1, N+1)]  # [1, 2, ..., N]
num=0 # 제거 할 인덱스

while len(arr)!=0:
    num+=K-1

    if num>=len(arr):
        num=num%len(arr)
    answer.append(str(arr.pop(num)))

print("<", end="")
print(", ".join(answer), end="")
print(">", end="")
